server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1
        - id: feedback-service
          uri: lb://FEEDBACKSERVICE
          predicates:
            - Path=/api/feedback/**
          filters:
            - StripPrefix=1
        - id: location-service
          uri: lb://LOCATIONSERVICE
          predicates:
            - Path=/api/locations/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
        - id: train-service
          uri: lb://TRAINSERVICE
          predicates:
            - Path=/api/trains/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG